ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Models/Temas.cs
using System;
using System.Collections.Generic;

namespace ManualesElectronicosFInalFinal2.Models
{
    public partial class Temas
    {
        public Temas()
        {
            Subtemas = new HashSet<Subtemas>();
        }

        public int Id { get; set; }
        public string Encabezado { get; set; }

        public ICollection<Subtemas> Subtemas { get; set; }
    }
}

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Controllers/DocentesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManualesElectronicosFInalFinal2.Helpers;
using ManualesElectronicosFInalFinal2.Models;
using ManualesElectronicosFInalFinal2.Models.DocentesViewModels;
using ManualesElectronicosFInalFinal2.Repositories;
    using Microsoft.AspNetCore.Mvc;

namespace ManualesElectronicosFInalFinal2.Controllers
{
    public class DocentesController : Controller
    {
      
        DocentesRepository doc;
        public IActionResult Docentes()
        {
            doc = new DocentesRepository();
            DocenteViewModel nom = new DocenteViewModel();
            nom.docentes = doc.GetDocentesxNombre();
            return View(nom);
        }





        [HttpPost]
        public JsonResult Agregar(DocenteViewModel nuevo)
        {



            doc = new DocentesRepository();
            JsonResult json = null;

            List<string> errores = doc.ValidarDocentes(nuevo.Docente);
            nuevo.Docente.Nombre = nuevo.Docente.Nombre.ToUpper();



            try
            {
                if (errores.Count() == 0)
                {

                    nuevo.Docente.Eliminado = false;
                    nuevo.Docente.Contraseña = EncriptarLaContraseñaConverter.Encriptar(nuevo.Docente.NumeroDeControl);
                    doc.Insert(nuevo.Docente);
                    json = Json(true);
                }

                for (int i = 0; i < errores.Count; i++)
                {
                    json = Json(errores);
                }
            }

            catch (Exception ex)
            {
                json = Json(ex.Message);
            }

            return json;
        }







        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            JsonResult json = null;
            DocentesRepository doc = new DocentesRepository();

            var datos = doc.GetDocenteById(id);
            List<string> errores = doc.ValidarDocentes(datos);
            try
            {
                //DocentesRepository doc = new DocentesRepository();
                //var r = doc.GetDocenteById(id);
                if (errores.Count() == 0)
                {
                    doc.Delete(datos);
                    json = Json(true);
                }
                else
                {
                    json = Json("El docente no existe o ya ha sido eliminado.");
                }
            }

            catch (Exception ex)
            {
                json = Json(ex.Message);
            }

            return json;
        }

        [HttpPost]

        public JsonResult GetDocente(int id)
        {
            JsonResult json = null;
            DocentesRepository doce = new DocentesRepository();
            var doc = doce.GetById(id);

            if (doc == null)
            {
                json = Json(false);
            }
            else
            {
                json = Json(
                    new
                    {
                        doc.Id,
                        doc.Nombre,
                        doc.NumeroDeControl,
                        doc.IdCarrera,
                        doc.Contraseña
                    }


                    );
            }
            return json;

        }
    




        [HttpPost]
        public JsonResult EditarDocentes(DocenteViewModel d)
        {

            JsonResult json = null;
            DocentesRepository doc = new DocentesRepository();
            d.Docente.Nombre = d.Docente.Nombre.ToUpper();
            List<string> errores = doc.ValidarDocentes(d.Docente);


         
                try
                {

                if (errores.Count() == 0)
                {
                    if (d != null)
                    {



                        doc.Update(d.Docente);
                        json = Json(true);
                    }

                    else
                    {
                        json = Json("El docente no existe o ya ha sido eliminado.");
                    }
                }
                        for (int i = 0; i < errores.Count; i++)
                        {
                            json = Json(errores);
                        }

                    
                }

                catch (Exception )
                {
                    json = Json("El docente no existe o fue eliminado anteriormente");
                }
                return json;

        }

    }
}

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Controllers/SubtemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManualesElectronicosFInalFinal2.Models;
using ManualesElectronicosFInalFinal2.Repositories;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;

namespace ManualesElectronicosFInalFinal2.Controllers
{
    public class SubtemasController : Controller
    {

        SubtemasRepository sub;
        public IActionResult Subtemas()
        {
            sub = new SubtemasRepository();
            ViewModelSubtemas su = new ViewModelSubtemas();

            su.Subtema = sub.GetSubemascxNombre();
            return View(su);
        }


        public IActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Agregar(ViewModelSubtemas s)
        {

            SubtemasRepository sub = new SubtemasRepository();
            JsonResult json = null;
            List<string> errores = sub.Validacion(s.Subtemas);
            try
            {
                if (errores.Count() == 0)
                {
                    s.Subtemas.Nombre = s.Subtemas.Nombre.ToUpper();

                    //nuevo.Alumno.Contraseña = EncriptarLaContraseñaConverter.Encriptar(nuevo.Alumno.NumeroControl);
                    sub.Insert(s.Subtemas);
                    json = Json(true);
                }

                for (int i = 0; i < errores.Count; i++)
                {
                    json = Json(errores);
                }
            }
            catch (Exception)
            {
                json = Json("Ah ocurrido un error, porfavor actualice la pagina y vuelva a intntarlo, si el error persiste comuniquese con soporte tecnico");
            }
            return json;




        }

        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            JsonResult json = null;
            try
            {
                SubtemasRepository sub = new SubtemasRepository();
                var r = sub.GetById(id);
                if (r != null)
                {
                    sub.Delete(r);
                    json = Json(true);
                }
                else
                {
                    json = Json("El curso no existe o ya ha sido eliminado.");
                }
            }
            catch (Exception)
            {
                json = Json("Ah ocurrido un error, porfavor actualice la pagina y vuelva a intntarlo, si el error persiste comuniquese con soporte tecnico");
            }


            return json;
        }

        public JsonResult GetSubtemas(int id)
        {
            JsonResult json = null;
            SubtemasRepository sub = new SubtemasRepository();
            var r = sub.GetById(id);
            if (r == null)
            {
                json = Json(false);
            }
            else
            {
                json = Json(
                    new
                    {
                        r.Id,
                        r.Nombre




                    }
                    );
            }
            return json;

        }
        [HttpPost]
        public JsonResult Editar(ViewModelSubtemas s)
        {
            JsonResult json = null;
            SubtemasRepository sub = new SubtemasRepository();

            List<string> errores = sub.Validacion(s.Subtemas);

            try
            {
                if (errores.Count() == 0)
                {
                    if (s != null)
                    {
                        s.Subtemas.Nombre = s.Subtemas.Nombre.ToUpper();
                        sub.Update(s.Subtemas);
                        json = Json(true);
                    }
                    else
                    {
                        json = Json("El Subtema no existe o ya ha sido eliminado.");
                    }
                }


                for (int i = 0; i < errores.Count; i++)
                {
                    json = Json(errores);
                }
                //  }
            }

            catch (Exception)
            {
                json = Json("Ah ocurrido un error, porfavor actualice la pagina y vuelva a intntarlo,a si el error persiste comuniquese con soporte tecnico");
            }
            return json;

        }

    }
}

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Controllers/TemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManualesElectronicosFInalFinal2.Models;
using ManualesElectronicosFInalFinal2.Models.DocentesViewModels;
using ManualesElectronicosFInalFinal2.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ManualesElectronicosFInalFinal2.Controllers
{
    public class TemasController : Controller
    {
        public TemasRepository temas;
        public SubtemasRepository sub;
        List<Subtemas> lista = new List<Subtemas>();
        public IActionResult Temas(int id)
        {
            temas = new TemasRepository();
            sub = new SubtemasRepository();
            ViewModelTemas tem = new ViewModelTemas();
            SubtemasViewModel su = new SubtemasViewModel();
            NavigationTemasSubtemas na = new NavigationTemasSubtemas();
            //su.Subtema = sub.GetSubemascxNombre();
            tem.Tema = temas.GetTemascxNombre();
            su.Subtema = sub.GetSubemascxNombre();
            //    su.Subtema = sub.GetSubemascxNombre();
           lista = new List<Subtemas>();
            ViewBag.SubBag = sub.GetSubemascxNombre();
       
            return View(tem);
        }


        public IActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Agregar(ViewModelTemas t)
        {

            TemasRepository tem = new TemasRepository();
            JsonResult json = null;
            List<string> errores = tem.Validacion(t.Temas);
            try
            {
                if (errores.Count() == 0)
                {
                    t.Temas.Encabezado = t.Temas.Encabezado.ToUpper();

                    //nuevo.Alumno.Contraseña = EncriptarLaContraseñaConverter.Encriptar(nuevo.Alumno.NumeroControl);
                    tem.Insert(t.Temas);
                    json = Json(true);
                }

                for (int i = 0; i < errores.Count; i++)
                {
                    json = Json(errores);
                }
            }
            catch (Exception)
            {
                json = Json("Ah ocurrido un error, porfavor actualice la pagina y vuelva a intntarlo, si el error persiste comuniquese con soporte tecnico");
            }
            return json;

        }


        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            JsonResult json = null;
            try
            {
                TemasRepository tem = new TemasRepository();
                var r = tem.GetById(id);
                if (r != null)
                {
                    tem.Delete(r);
                    json = Json(true);
                }
                else
                {
                    json = Json("El curso no existe o ya ha sido eliminado.");
                }
            }
            catch (Exception)
            {
                json = Json("Ah ocurrido un error, porfavor actualice la pagina y vuelva a intntarlo, si el error persiste comuniquese con soporte tecnico");
            }


            return json;
        }
        public JsonResult GetTemas(int id)
        {
            JsonResult json = null;
            TemasRepository tem = new TemasRepository();
            var r = tem.GetById(id);
            if (r == null)
            {
                json = Json(false);
            }
            else
            {
                json = Json(
                    new
                    {
                        r.Id,
                        r.Encabezado




                    }
                    );
            }
            return json;

        }

        [HttpPost]
         public JsonResult Editar(ViewModelTemas t)
          {
            JsonResult json = null;
            TemasRepository tem = new TemasRepository();
            
            List<string> errores = tem.Validacion(t.Temas);

            try
            {
                if (errores.Count() == 0)
                {
                    if (t != null)
                    {
                        t.Temas.Encabezado = t.Temas.Encabezado.ToUpper();
                        tem.Update(t.Temas);
                        json = Json(true);
                    }
                    else
                    {
                        json = Json("El Tema no existe o ya ha sido eliminado.");
                    }
                }


                for (int i = 0; i < errores.Count; i++)
                {
                    json = Json(errores);
                }
                //  }
            }

            catch (Exception)
            {
                json = Json("Ah ocurrido un error, porfavor actualice la pagina y vuelva a intntarlo,a si el error persiste comuniquese con soporte tecnico");
            }
            return json;

        }
    }
}

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Views/Temas/EditarTema.cshtml
@{
    ViewData["Title"] = "EditarTema";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="~/Views/Cursos/style.css" rel="stylesheet" />
</head>
<body>
    <section>
        <form>
            <div>
                <h2>Editar Tema</h2>
            </div>            
            <input type="text" placeholder="El nombre del tema" /><br />

            <select></select>

            <div>
                <input type="submit" value="Editar" />
                <button>Cancelar</button>

            </div>
            <div>
                <p>@Html.ValidationSummary()</p>
            </div>
        </form>
    </section>
</body>
</html>

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Views/Temas/EditarTemas.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditarTemas</title>
</head>
<body>
</body>
</html>

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Views/Temas/EditarTemass.cshtml
@model Temas
@{
    ViewData["Title"] = "EditarTemass";
  
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditarTemas1</title>
</head>
<body>
    <style>
        body {
            background: #2f313d;
            font-family: sans-serif;
            font-size: 20px;
        }

        h2 {
            color: whitesmoke;
            font-size: 30px;
            text-align: center;
            margin-bottom: 10px;
        }

        form {
            width: 50%;
            position: absolute;
            left: 22%;
            background: rgba(0,0,0,0.3);
            padding: 20px 30px;
            color: whitesmoke;
            border-radius: 15px;
        }

        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 15px 0px;
            background: transparent;
            border: 0;
            border-bottom: 1px solid rgba(255,255,255,0.04);
            outline: none;
            color: white;
            font-size: 12px;
        }

        input[type="submit"], button {
            background: #008F63;
            border: 0;
            width: 250px;
            height: 40px;
            border-radius: 3px;
            color: white;
            cursor: pointer;
            transition: background 0.3s ease-in-out;
            font-size: 20px;
            margin: 40px;
        }
    </style>
    <form method="post" asp-action="EditarTemass" asp-controller="Temas">
        <div>
            <h2>Editar Temas</h2><br />
            @*<label>Nombre Docente:</label><br />*@

            <input type="hidden" id="id" asp-for="Id" />

            <input type="text" id="Encabezado" asp-for="@Model.Encabezado" placeholder="@Model.Encabezado" />


            <br />


            <input type="submit" value="Agregar" />
            <button asp-action="Temas">Cancelar</button>
        </div>
    </form>
</body>
</html>

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Views/Temas/Eliminar.cshtml
@model Temas
@{
    ViewData["Title"] = "EliminarTema";
}

<link href="~/Views/Docentes/style.css" rel="stylesheet" />
<style>
    body {
        background: #2f313d;
        font-family: sans-serif;
        font-size: 20px;
    }

    p {
        font-size: 20px;
        color: darkred;
    }

    h2, h1 {
        color: whitesmoke;
        font-size: 30px;
        text-align: center;
        margin-bottom: 10px;
    }

    form {
        width: 50%;
        position: absolute;
        left: 22%;
        background: rgba(0,0,0,0.3);
        padding: 20px 30px;
        color: whitesmoke;
        border-radius: 15px;
    }

    input[type="submit"], input[type="button"] {
        background: #008F63;
        border: 0;
        width: 250px;
        height: 40px;
        border-radius: 3px;
        color: white;
        cursor: pointer;
        transition: background 0.3s ease-in-out;
        font-size: 20px;
        margin: 40px;
    }
</style>
<form method="post" asp-action="Eliminar" asp-controller="Temas">
    <div>
        <h1>Eliminar Tema</h1>

    
        <input type="hidden" id="id" asp-for="Id" />
        <p>¿Está seguro de eliminar el tema:? @Model.Encabezado</p>

        <div class="botones">
            <p>
                @Html.ValidationSummary()
            </p>
            <input type="submit" value="Si" />
            <input type="button" value="No" />
        </div>
    </div>
</form>

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Views/Temas/EliminarTema.cshtml
@{
    ViewData["Title"] = "EliminarTema";
}

<link href="~/Views/Docentes/style.css" rel="stylesheet" />
<style>
    body {
        background: #2f313d;
        font-family: sans-serif;
        font-size: 20px;
    }

    p {
        font-size: 20px;
        color: darkred;
    }

    h2, h1 {
        color: whitesmoke;
        font-size: 30px;
        text-align: center;
        margin-bottom: 10px;
    }

    form {
        width: 50%;
        position: absolute;
        left: 22%;
        background: rgba(0,0,0,0.3);
        padding: 20px 30px;
        color: whitesmoke;
        border-radius: 15px;
    }

    input[type="submit"], input[type="button"] {
        background: #008F63;
        border: 0;
        width: 250px;
        height: 40px;
        border-radius: 3px;
        color: white;
        cursor: pointer;
        transition: background 0.3s ease-in-out;
        font-size: 20px;
        margin: 40px;
    }
</style>
<form method="post" asp-action="Eliminar" asp-controller="Docentes">
    <div>
        <h1>Eliminar Tema</h1>

        <input type="hidden"/>

        <p>¿Está seguro de eliminar el tema:? </p>

        <div class="botones">
            <p>
                @Html.ValidationSummary()
            </p>
            <input type="submit" value="Si"/>
            <input type="button" value="No"/>
        </div>
    </div>
</form>

ManualesElectronicosFInalFinal2/ManualesElectronicosFInalFinal2/Views/Temas/Temas.cshtml
@model ManualesElectronicosFInalFinal2.Models.ViewModelTemas
@*@inject TemasServices service*@
@*@inject ManualesElectronicosFInalFinal2.Services.TemasServices servicio*@


    @{
        ViewData["Title"] = "Temas";
        Layout = "~/Views/Shared/Layout.cshtml";
    }
    <html>
    <head>
        <meta charset="utf-8" />
        <link href="~/Content/estilos.css" rel="stylesheet" />
        <link href="~/Content/grid.css" rel="stylesheet" />
        <link href="~/Content/StyleSheet.css" rel="stylesheet" />
        <link href="~/Content/OtrosColores.css" rel="stylesheet" />
        <!-- Para usar iconos con FontAwesome  -->
        <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>

        <link href="~/Content/sidebar.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <script src="jquery-3.5.0.min"></script>
        <script src="util.js"></script>


        <title>Temas</title>
    </head>
    <body>

        <nav class="menu" id="sidebar">
            <div>
            </div>
            <ul>
                <li><a asp-action="Docentes" asp-controller="Docentes"><i class="fa fa-address-card"></i>Administrar Docentes</a></li>
                <li><a asp-action="Alumnos" asp-controller="Alumnos"><i class="fa fa-address-card"></i>Administrar Alumnos</a></li>
                <li><a asp-action="Cursos" asp-controller="Cursos"><i class="fas fa-book"></i>Administrar Cursos</a></li>
                <li><a><i class="fas fa-book"></i>Compartir Cursos</a></li>
                <li><a><i class="fa fa-address-card"></i>Enrrolar Alumnos</a></li>

            </ul>

        </nav>
        <header>
            <a href="#" class="toggle-btn"><i class="fa fa-bars"></i></a>
            <h1 style="color:white; width:auto; border-bottom:none; text-align:center;"><b>ITESRC</b> Manuales Electronicos</h1>
            <div class="dropdown">
                <a href="#" class="right">
                    <i class="fa fa-user"></i>
                </a>
                <ul>
                    <li><a style="text-decoration: none; color:black;" href="#"><i class="fa fa-key"></i>Cambiar Contraseña</a></li>
                    <li><a style="text-decoration: none; color:black;" href="#"><i class="fa fa-sign-out-alt"></i> Cerrar Sesión</a></li>
                </ul>
            </div>
        </header>
        <main id="contenido">
            <div>
                <h2 style=" float:right;  margin-top:15px; "> <a href="javascript:showModal('modalAgregar')" style="color:white;"><i class="fas fa-plus-circle"></i></a></h2>
            </div>
            <section>

                <div   >
                    @foreach (var item in Model.Tema)
                    {
                        IEnumerable<Subtemas> lista = ViewBag.SubBag;
                      
                        <h2 type="button" class="collapsible" id="@item.Id" onclick="@item.Id" >
                            @item.Encabezado
                            @item.Id
                            <a href="javascript:editar(@item.Id)" style="margin-left:5px;"><i class="fas fa-edit"></i></a>
                            <a href="javascript:eliminar(@item.Id)"><i class="fa fa-trash"></i></a>
                        </h2>
                        ViewBag.idd = item.Id;
                        //service.GetNombreSubtemas()


                        <div class="content">
                            @foreach (var itemm in lista)
                            {

                                <div class="subtemas">
                                    <a href="#"></a>
                                    @itemm.Nombre
                                    @item.Id
                                    <a href="javascript:editarr(@itemm.Id)" style="margin-left:5px; float:right;"><i class="fas fa-edit"></i></a>
                                    <a href="javascript:eliminarr(@itemm.Id)" style="float: right;"><i class="fa fa-trash"></i></a>
                                    <a href="javascript:showModal('modalAgregarr')" style="float: right;"><i class="fas fa-plus-circle"></i></a>

                                </div>

                            }
                        </div>

                    }
                </div>


            </section>
            <div class="modal" id="modalAgregar">
                <section>
                    <h2>Agregar Tema</h2>

                    <form class="formAjax" method="post" action="~/Temas/Agregar">
                        <label class="col-2">Nombre:</label>
                        <input class="col-10" type="text" asp-for="Temas.Encabezado" required="required" />
                        <label class="col-12 error"></label>

                        <a href="~/Temas/Temas">
                            <input type="button" value="Cancelar" />
                        </a>
                        <input type="submit" value="Agregar" />
                    </form>
                </section>
            </div>
            <div class="modal" id="modalEditar">
                <section>
                    <h2>Editar Tema</h2>

                    <form class="formAjax" method="post" action="~/Temas/Editar">
                        <input id="editId" type="hidden" asp-for="Temas.Id" />
                        <label class="col-2">Nombre:</label>
                        <input id="editNombre" class="col-10" type="text" asp-for="Temas.Encabezado" required="required" />
                        <label class="col-12 error"></label>
                        <a href="~/Temas/Temas">
                            <input type="button" asp-action="Temas" class="cancel" value="Cancelar" />
                        </a>

                        <input type="submit" value="Agregar" />
                    </form>
                    <script>
                function editar(id) {


			$.post('@Url.Action("GetTemas", "Temas")', { "id": id }, function (data, status) {
				if (data != false) {


                    var x = $("#modalEditar form");

					x.find("#editId").val(data.id);
                    x.find("#editNombre").val(data.encabezado);

					showModal("modalEditar");
				}
			});
		}
                    </script>
                </section>
            </div>
            <div id="modalEliminar" class="modal">
                <section>
                    <h2>Confirme la eliminación</h2>

                    <form class="formAjax" method="post" action="~/Temas/Eliminar">
                        <input id="deleteId" type="hidden" name="Id" />
                        <p>¿Esta seguro de eliminar?</p>


                        <label class="col-12 error"></label>

                        <a href="~/Temas/Temas">
                            <input type="button" value="No" class="cancel" />
                        </a>
                        <input type="submit" value="Si" />
                    </form>
                    <script>
                        function eliminar(id) {
                            $("#deleteId").val(id);
                            showModal("modalEliminar");

                        }

                    </script>
                </section>
            </div>


            <div class="modal" id="modalAgregarr">
                <section>
                    <h2>Agregar Subtema</h2>

                    <form class="formAjax" method="post" action="~/Subtemas/Agregar">
                        <label class="col-2">Nombre:</label>
                        <input   value="@ViewBag.idd"  asp-for="Subtemas.IdTemas" />
                        <input class="col-10" type="text" asp-for="Subtemas.Nombre" required="required" />
                        <label class="col-12 error"></label>
                        <a href="~/Temas/Temas">
                            <input type="button" value="Cancelar" />
                        </a>
                        <input type="submit" value="Agregar" />
                    </form>
                </section>
            </div>
            <div class="modal" id="modalEditarr">
                <section>
                    <h2>Editar Subtema</h2>
                    
                    <form class="formAjax" method="post" action="~/Subtemas/Editar">
                        <input id="editId" type="hidden" asp-for="Subtemas.Id" />
                        <label class="col-2">Nombre:</label>
                        <input id="editNombre" class="col-10" type="text" asp-for="Subtemas.Nombre"  required="required" />
                        <label class="col-12 error"></label>

                        <input type="button" class="cancel" value="Cancelar" />
                        <input type="submit" value="Agregar" />
                    </form>
                    <script>
                    function editarr(id) {


                $.post('@Url.Action("GetSubtemas", "Subtemas")', { "id": id }, function (data, status) {
                    if (data != false) {


                        var x = $("#modalEditarr form");

                        x.find("#editId").val(data.id);
                        x.find("#editNombre").val(data.nombre);

                        showModal("modalEditarr");
                    }
                });
            }
                    </script>
                </section>
            </div>
            <div id="modalEliminarr" class="modal">
                <section>
                    <h2>Confirme la eliminación</h2>

                    <form class="formAjax" method="post" action="~/Subtemas/Eliminar">
                        <input id="deleteIdd" type="hidden" name="Id" />
                        <p>¿Esta seguro de eliminar?</p>


                        <label class="col-12 error"></label>
                        <a href="~/Temas/Temas">
                            <input type="button" value="No" class="cancel" />
                        </a>  <input type="submit" value="Si" />
                    </form>
                    <script>
                        function eliminarr(id) {
                            $("#deleteIdd").val(id);
                            showModal("modalEliminarr");

                        }

                    </script>
                </section>
            </div>

        </main>
        <script src="~/main.js">


        </script>
        <script src="~/temas.js"></script>
    </body>
</html>